### ISSUE TITLE
Examples of vignettes using rlp package

### ISSUE THREAD

**Issue by MarcinKosinski** [yihui/rlp#1]
Hi!

First of all I'd like to say I'm amazed by this package. It is brilliant that I can make vignette, documentation and functions at one time in 1 file :)! Moreover, documentation possibilities have never been so broad for me, since I've discovered `rlp` package few months ago.

I am writing this issue because I will lead workshops on `Creating packages with rlp package` at Warsaw University of Technology because of  `workshops on the processing and presentation of data` that we lead for free with my friends from `Data Science Students Union` and `foundation for statistics SmarterPoland.pl` : here is the [event on facebook](https://www.facebook.com/events/879549242126491/), unfortunately in polish.

I am writing to ask you, have you ever seen someone else, besides you, that have created a vignette to his package using your's `rlp` package? I would like to show some original solutions on how brilliant can documenting with `rlp` be. I've seen [your's example](http://yihui.name/rlp/) but maybe there are more.

I was thinking on making my own vignette for demonstration purpose and I was thinking on inserting images into vignette, as it's just a regular html. What do you think about this? I also thought I can create a vignette with shiny app inside it or with a movie/film on `youtube.com` with instructions on how to use this `demonstration-purpose-workshop-package` :) What do you think about that? Is it even possible?

Finally, I have last question about your opinion. Do you really think that all functions should be documented with `rlp`? Imagine a package so wealthy in number of function as `base`. Such vignette would be amazingly long and useless. I thought that vignette should be a tutorial through your package and shows only functionalities and main features of a package, but not every single nook of a code. What do you think about that :)? Is there really any sense to write whole package in `rlp`? This would be the last question I would like to ask the audience during workshop and I'm curious about your opinion.

Thanks for response,
Best,
Marcin

**Comment by yihui** [comment]
Thanks for the kind words. I think I have answered your last few questions at http://yihui.name/rlp/ I don't think all functions should be written this way. In this package, you can see the script R/hello.R, which is just a normal R script (not generated from .Rmd like other .R scripts).

Re other people's examples, no, I'm not aware of any. I have never really mentioned this package in the public, so I guess a lot of people are not aware of this possibility.

For Youtube videos, of course you can do it.

For Shiny apps, I think your best bet is to deploy the app to a server (e.g. ShinyApps.io), and embed it by `<iframe>`.

**Comment by MarcinKosinski** [comment]
Hi!

Thanks for your answer.

I've read your example at http://yihui.name/rlp/ where you state

> In other words, we use LP to document the usage of software, instead of documenting the source > code. See Doxygen, Javadoc, and roxygen2 for examples.

Where on [wikipedia](http://en.wikipedia.org/wiki/Literate_programming) to which you also gave a link at the beginning states:

> This misconception has led to claims that comment-extraction tools, such as the Perl Plain Old Documentation or Java Javadoc systems, are "literate programming tools". However, because these tools do not implement the "web of abstract concepts" hiding behind the system of natural-language macros, or provide an ability to change the order of the source code from a machine-imposed sequence to one convenient to the human mind, they cannot properly be called literate programming tools in the sense intended by Knuth

What about that :) ?

**Comment by yihui** [comment]
I agree with the comment on Wikipedia. I have shown that in Section 8.

**Comment by MarcinKosinski** [comment]
If you're interested I've prepared such presentation for workshop on rlp :)
http://mi2-warsaw.github.io/extremeMetrics/#1

**Comment by yihui** [comment]
Looks great. Thanks!
